### ISSUE TITLE
Incluir uma busca de filmes independente das preferências

### ISSUE THREAD

**Issue by tatidias** [DigitalHouseBrasil/Mobile04#95]

**Comment by francorufino** [comment]
onde????????

**Comment by tatidias** [comment]
Seria uma home de todos os filmes, a home criada tem apenas os filmes das 4 preferencias.


De: ANDREZA CAMPBELL <notifications@github.com>
Enviada em: segunda-feira, 5 de novembro de 2018 17:59
Para: DigitalHouseBrasil/Mobile04 <Mobile04@noreply.github.com>
Cc: Tatiana Miranda Dias <Tati.m.d@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [DigitalHouseBrasil/Mobile04] Incluir uma busca de filmes independente das preferências (#95)


onde????????
